eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8010/eureka}

---
spring:
  profiles: subject
words: I,You,He,She,It
server:
  port: 8012

---
spring:
  profiles: verb
words: ran,knew,had,saw,bought
server:
  port: 8013

---
spring:
  profiles: article
words: a,the
server:
  port: 8014

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely
server:
  port: 8015

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog
server:
  port: 8016
