eureka:
  client:
    serviceUrl:
       defaultZone: http://localhost:9004/eureka/
#        defaultZone: http://eureka-secondary:9004/eureka/,http://eureka-secondary:9002/eureka/,http://eureka-tertiary:9003/eureka/



---
spring:
  profiles: subject
  application:
    name: LAB-4-SUBJECT
words: I,You,He,She,It
server:
  port: 8012


---
spring:
  profiles: verb
  application:
    name: LAB-4-VERB
words: ran,knew,had,saw,bought
server:
  port: 8013

---
spring:
  profiles: article
  application:
    name: LAB-4-ARTICLE
words: a,the
server:
  port: 8014

---
spring:
  profiles: adjective
  application:
    name: LAB-4-ADJECTIVE
words: reasonable,leaky,suspicious,ordinary,unlikely
server:
  port: 8015

---
spring:
  profiles: noun
  application:
    name: LAB-4-NOUN
words: boat,book,vote,seat,backpack,partition,groundhog
server:
  port: 8016
